name: Build APK

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.gradle'
      - '**build.gradle'
      - '**settings.gradle'
      - '.github/workflows/build_apk.yml'
      - 'project/android/**'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**.gradle'
      - '**build.gradle'
      - '**settings.gradle'
      - '.github/workflows/build_apk.yml'
      - 'project/android/**'

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Initialize Gradle wrapper
        run: ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk